### ISSUE TITLE
tags are gone in pro 2023

### ISSUE THREAD

**Issue by robindelange** [caseda/com.nodon#23]
hi, Remco 

I used the tags from my Nodon soft switch to increase volume of my Sonos, but now the tags don't work anymore.
as you can see the tags are grey, they worked flawless before. I don't know if this is a HP2023 problem or an app problem.

can you help me?
<img width="432" alt="Schermafbeelding 2023-05-12 om 00 38 50" src="https://github.com/caseda/com.nodon/assets/79162166/1b0292bd-fa9d-4171-8d0d-d9e089ffd9f2">

**Comment by caseda** [comment]
That's a new one for me.
What Homey version (which RC) is this happening on?
And could you send me an app report? (mobile app -> more... -> Apps -> NodOn -> Cogwheel (top right) -> create diagnostic report).

**Comment by robindelange** [comment]
I dont know which RC this happend because with the other zwave problems the devices didnt work properply. Know they are fixed i noticed this problem

im now on the latest RC 105

Report: bc0e5c66-1fef-4fdf-84f3-b6950d822570

**Comment by caseda** [comment]
Hmm, not seeing any error popup in your report.
So i'll have to dig in a bit deeper.
Thanks for reporting though.

**Comment by robindelange** [comment]
Oke, you’re welcome👍🏻

**Comment by caseda** [comment]
it should be fixed in the test version of the app (v3.0.3), if you would be so kind to test this version:

https://homey.app/a/com.nodon/test

**Comment by robindelange** [comment]
Yes, I have my tags back! Thank you very much!

**Comment by robindelange** [comment]
maybe you can also answer my follow question, the nodon soft remote is the only devices that doesn't always report/send actions. sometimes I have to push several times on the button before the action is coming true at homey ( tested with push notification and tags)

my routering is good I think, I have a Aeotec zwave repeater 2 meter away from it and +- 1 meter of the remote is a Aeotec smart switch 6 which also Is a router.  also In the shower I have a other zwave button (robbshop wallswich) and this one works almost always. 

now im looking on Dev page and see the that the error value of the soft remote is very high, do you know a solution for this problem? 
<img width="903" alt="Schermafbeelding 2023-05-16 om 14 55 19" src="https://github.com/caseda/com.nodon/assets/79162166/fe655df4-d7d4-415d-936d-7f2e880672b5">

**Comment by caseda** [comment]
If you hold it closer to Homey does it start/keep working?
Even if you have a repeater and a switch 7, that's not a very big mesh, the bathroom is very known for being isolating for radio waves as the entire floor is technically grounded by a mesh (looking at your naming scheme you live in the Netherlands where this is mandatory), have that myself with a power plug which routes through several nodes to reach Homey, if I place it just outside the bathroom it works without any routing at all.

**Comment by robindelange** [comment]
there are 3 routers on the 1e floor, and 1 in the bathroom.

yes I live in the Netherlands, just tested the soft remote downstairs, but still doesn't work good.  just restart homey and looking at dev page when I test the device on the dev page it says its unreachable. even when I wake it up before test.
<img width="1280" alt="Schermafbeelding 2023-05-16 om 18 00 10" src="https://github.com/caseda/com.nodon/assets/79162166/5de0aebd-9c57-42a8-bf8b-d13c28affaeb">

**Comment by robindelange** [comment]
strange thing is that other buttons also say its unreachable but do work fast and reliable, even the other button (badkamer wandknop)

**Comment by caseda** [comment]
hmm, have you tried replacing the battery? the battery level displayed in the app doesn't always work properly, and have seen in my octan remote that the battery also displayed green, but didn't work properly either until I replaced the battery.

**Comment by robindelange** [comment]
Yes, it came also to my mind this evening. After that it worked well, but i dont know for how long. Strange thing is that the other battery showed 84% and when i took it out and meassured it it give 2,95 volts. Not that bad.

**Comment by caseda** [comment]
Battery starts around 3.3/3.2V and is low at 2.85/2.8V so yeah it should have a bit left, but not a lot.
But that's not something this app can fix though, neither any communication between the device and Homey, as that is done by the Z-Wave core.
So I guess we can call this fixed for now, thanks for the verification test.
If you have more issues with the app feel free to open another issue.

**Comment by robindelange** [comment]
Thank you for your help and the quick fix
